"""
models/__init__.py — raw SQL DDL helpers.
No ORM; tables are created directly via psycopg2.
"""

CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    full_name     VARCHAR(150)  NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS roles (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_USER_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);
"""

SEED_ROLES = """
INSERT INTO roles (name)
VALUES ('Admin'), ('Cashier')
ON CONFLICT (name) DO NOTHING;
"""


def init_db(conn) -> None:
    """Create all tables if they do not exist, then seed base roles."""
    with conn.cursor() as cur:
        cur.execute(CREATE_USERS_TABLE)
        cur.execute(CREATE_ROLES_TABLE)
        cur.execute(CREATE_USER_ROLES_TABLE)
        cur.execute(SEED_ROLES)
    conn.commit()
