"""
models/__init__.py — raw SQL DDL helpers.
No ORM; tables are created directly via psycopg2.
"""

CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    full_name     VARCHAR(150)  NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS roles (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_USER_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);
"""

CREATE_PRODUCTS_TABLE = """
CREATE TABLE IF NOT EXISTS products (
    id              BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id         VARCHAR(50)   UNIQUE,
    product_category VARCHAR(50)  NOT NULL,
    subcategory     VARCHAR(50),
    barcode         VARCHAR(50)   UNIQUE,
    name            VARCHAR(200)  NOT NULL,
    brand           VARCHAR(100),
    expiry_date     DATE,
    price           DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    stock_quantity  INTEGER       NOT NULL DEFAULT 0,
    unit            VARCHAR(20)   NOT NULL DEFAULT 'pcs',
    description     TEXT,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

SEED_ROLES = """
INSERT INTO roles (name)
VALUES ('Admin'), ('Cashier')
ON CONFLICT (name) DO NOTHING;
"""


def init_db(conn) -> None:
    """Create all tables if they do not exist, then seed base roles."""
    with conn.cursor() as cur:
        cur.execute(CREATE_USERS_TABLE)
        cur.execute(CREATE_ROLES_TABLE)
        cur.execute(CREATE_USER_ROLES_TABLE)
        cur.execute(CREATE_PRODUCTS_TABLE)
        cur.execute(SEED_ROLES)
    conn.commit()
