"""
models/__init__.py — raw SQL DDL helpers.
No ORM; tables are created directly via psycopg2.
"""

CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100)  NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    full_name     VARCHAR(150)  NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS roles (
    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_CATEGORIES_TABLE = """
CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_USER_ROLES_TABLE = """
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);
"""

CREATE_PRODUCTS_TABLE = """
CREATE TABLE IF NOT EXISTS products (
    id                  BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(150) NOT NULL,
    barcode             VARCHAR(64)  UNIQUE,
    brand               VARCHAR(100),
    category_id         BIGINT      NOT NULL,
    subcategory         VARCHAR(100),
    unit                VARCHAR(30)  NOT NULL,
    purchase_price      NUMERIC(12,2) NOT NULL,
    mrp                 NUMERIC(12,2) NOT NULL,
    selling_price       NUMERIC(12,2) NOT NULL,
    gst_percentage      NUMERIC(5,2)  NOT NULL,
    current_stock       NUMERIC(12,3) NOT NULL DEFAULT 0,
    minimum_stock_level NUMERIC(12,3) NOT NULL DEFAULT 0,
    quick_sale_enabled  BOOLEAN     NOT NULL DEFAULT FALSE,
    active              BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
"""

CREATE_PRODUCTS_INDEXES = """
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
"""

SEED_ROLES = """
INSERT INTO roles (name)
VALUES ('Admin'), ('Cashier')
ON CONFLICT (name) DO NOTHING;
"""


def init_db(conn) -> None:
    """Create all tables if they do not exist, then seed base roles."""
    with conn.cursor() as cur:
        cur.execute(CREATE_USERS_TABLE)
        cur.execute(CREATE_ROLES_TABLE)
        cur.execute(CREATE_USER_ROLES_TABLE)
        cur.execute(CREATE_CATEGORIES_TABLE)
        cur.execute(CREATE_PRODUCTS_TABLE)
        cur.execute(CREATE_PRODUCTS_INDEXES)
        cur.execute(SEED_ROLES)
    conn.commit()
