import os
import urllib.parse
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent / ".env")

import jwt
import psycopg2
from psycopg2.extras import RealDictCursor
from flask import Flask, request, jsonify
from flask_cors import CORS
from passlib.context import CryptContext
from werkzeug.security import check_password_hash as werkzeug_check

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = Flask(__name__)
CORS(app)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

VALID_ROLES   = ("Admin", "Cashier")
JWT_SECRET    = os.environ.get("SECRET_KEY", "dev-secret-key")
JWT_ALGORITHM = "HS256"
JWT_EXP_HOURS = 12

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _get_dsn() -> str:
    dsn = os.environ.get("DATABASE_URL", "")
    if not dsn:
        raise RuntimeError("DATABASE_URL not set")
    parsed = urllib.parse.urlparse(dsn)
    params = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
    params.pop("channel_binding", None)
    new_query = urllib.parse.urlencode({k: v[0] for k, v in params.items()})
    return parsed._replace(query=new_query).geturl()


def get_conn():
    return psycopg2.connect(_get_dsn(), connect_timeout=15)


def get_cur(conn):
    return conn.cursor(cursor_factory=RealDictCursor)


# ---------------------------------------------------------------------------
# DB init — runs once per cold start
# ---------------------------------------------------------------------------

_db_ready = False
_db_version = 3   # bump this to force re-run migrations on next cold start


def ensure_db():
    global _db_ready
    if _db_ready:
        return
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    username      VARCHAR(100) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    full_name     VARCHAR(150) NOT NULL,
                    active        BOOLEAN      NOT NULL DEFAULT TRUE,
                    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS roles (
                    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name       VARCHAR(50) NOT NULL UNIQUE,
                    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS user_roles (
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    role_id BIGINT NOT NULL REFERENCES roles(id),
                    PRIMARY KEY (user_id, role_id)
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS categories (
                    id          BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name        VARCHAR(100) NOT NULL UNIQUE,
                    description VARCHAR(255),
                    active      BOOLEAN     NOT NULL DEFAULT TRUE,
                    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS products (
                    id                  BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name                VARCHAR(150) NOT NULL,
                    barcode             VARCHAR(64)  UNIQUE,
                    brand               VARCHAR(100),
                    category_id         BIGINT      NOT NULL,
                    subcategory         VARCHAR(100),
                    unit                VARCHAR(30)  NOT NULL,
                    purchase_price      NUMERIC(12,2) NOT NULL,
                    mrp                 NUMERIC(12,2) NOT NULL,
                    selling_price       NUMERIC(12,2) NOT NULL,
                    gst_percentage      NUMERIC(5,2)  NOT NULL,
                    track_stock         BOOLEAN     NOT NULL DEFAULT TRUE,
                    current_stock       NUMERIC(12,3),
                    minimum_stock_level NUMERIC(12,3),
                    quick_sale_enabled  BOOLEAN     NOT NULL DEFAULT FALSE,
                    active              BOOLEAN     NOT NULL DEFAULT TRUE,
                    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_products_name ON products(name)")

            # ── Column migrations (safe ALTER TABLE for existing tables) ──────
            # Add track_stock if missing (tables created before this column was added)
            cur.execute("""
                ALTER TABLE products
                ADD COLUMN IF NOT EXISTS track_stock BOOLEAN NOT NULL DEFAULT TRUE
            """)
            # Add quick_sale_enabled if missing
            cur.execute("""
                ALTER TABLE products
                ADD COLUMN IF NOT EXISTS quick_sale_enabled BOOLEAN NOT NULL DEFAULT FALSE
            """)
            # Add minimum_stock_level if missing
            cur.execute("""
                ALTER TABLE products
                ADD COLUMN IF NOT EXISTS minimum_stock_level NUMERIC(12,3)
            """)
            # Add current_stock if missing
            cur.execute("""
                ALTER TABLE products
                ADD COLUMN IF NOT EXISTS current_stock NUMERIC(12,3)
            """)
            # Add payment_method + amount_tendered + change_amount to sales if missing
            cur.execute("""
                ALTER TABLE sales
                ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NOT NULL DEFAULT 'cash'
            """)
            cur.execute("""
                ALTER TABLE sales
                ADD COLUMN IF NOT EXISTS amount_tendered NUMERIC(12,2)
            """)
            cur.execute("""
                ALTER TABLE sales
                ADD COLUMN IF NOT EXISTS change_amount NUMERIC(12,2)
            """)
            # Ensure sale_time has a default on existing tables (was NOT NULL but no DEFAULT)
            cur.execute("""
                ALTER TABLE sales
                ALTER COLUMN sale_time SET DEFAULT CURRENT_TIMESTAMP
            """)
            # held_sales
            cur.execute("""
                CREATE TABLE IF NOT EXISTS held_sales (
                    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    hold_reference   VARCHAR(50)   NOT NULL UNIQUE,
                    cashier_username VARCHAR(100)  NOT NULL,
                    subtotal         NUMERIC(12,2) NOT NULL,
                    discount_total   NUMERIC(12,2) NOT NULL DEFAULT 0,
                    tax_total        NUMERIC(12,2) NOT NULL DEFAULT 0,
                    grand_total      NUMERIC(12,2) NOT NULL,
                    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS held_sale_items (
                    id              BIGINT         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    held_sale_id    BIGINT         NOT NULL REFERENCES held_sales(id) ON DELETE CASCADE,
                    product_id      BIGINT         NOT NULL REFERENCES products(id),
                    product_name    VARCHAR(150)   NOT NULL,
                    quantity        NUMERIC(12,3)  NOT NULL,
                    unit_price      NUMERIC(12,2)  NOT NULL,
                    discount_amount NUMERIC(12,2)  NOT NULL DEFAULT 0,
                    tax_amount      NUMERIC(12,2)  NOT NULL DEFAULT 0,
                    line_total      NUMERIC(12,2)  NOT NULL
                )
            """)
            # sales
            cur.execute("""
                CREATE TABLE IF NOT EXISTS sales (
                    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    invoice_number   VARCHAR(30)   NOT NULL UNIQUE,
                    cashier_username VARCHAR(100)  NOT NULL,
                    sale_time        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    subtotal         NUMERIC(12,2) NOT NULL,
                    discount_total   NUMERIC(12,2) NOT NULL DEFAULT 0,
                    tax_total        NUMERIC(12,2) NOT NULL DEFAULT 0,
                    round_off        NUMERIC(12,2) NOT NULL DEFAULT 0,
                    grand_total      NUMERIC(12,2) NOT NULL,
                    payment_method   VARCHAR(30)   NOT NULL DEFAULT 'cash',
                    amount_tendered  NUMERIC(12,2),
                    change_amount    NUMERIC(12,2),
                    status           VARCHAR(20)   NOT NULL DEFAULT 'completed',
                    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS sale_items (
                    id              BIGINT         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    sale_id         BIGINT         NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
                    product_id      BIGINT         NOT NULL REFERENCES products(id),
                    product_name    VARCHAR(150)   NOT NULL,
                    barcode         VARCHAR(64),
                    quantity        NUMERIC(12,3)  NOT NULL,
                    unit_price      NUMERIC(12,2)  NOT NULL,
                    discount_amount NUMERIC(12,2)  NOT NULL DEFAULT 0,
                    tax_amount      NUMERIC(12,2)  NOT NULL DEFAULT 0,
                    line_total      NUMERIC(12,2)  NOT NULL,
                    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            # inventory_transactions
            cur.execute("""
                CREATE TABLE IF NOT EXISTS inventory_transactions (
                    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    product_id       BIGINT        NOT NULL REFERENCES products(id),
                    transaction_type VARCHAR(20)   NOT NULL,
                    quantity_change  NUMERIC(12,3) NOT NULL,
                    stock_before     NUMERIC(12,3) NOT NULL,
                    stock_after      NUMERIC(12,3) NOT NULL,
                    reference_type   VARCHAR(50)   NOT NULL,
                    reference_id     VARCHAR(50)   NOT NULL,
                    remarks          VARCHAR(255),
                    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS idx_sales_invoice ON sales(invoice_number)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_held_sale_items_held ON held_sale_items(held_sale_id)")
            cur.execute("""
                INSERT INTO roles (name) VALUES ('Admin'), ('Cashier')
                ON CONFLICT (name) DO NOTHING
            """)

            # ── credit_bills table ────────────────────────────────────────────
            cur.execute("""
                CREATE TABLE IF NOT EXISTS credit_bills (
                    id               BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    customer_name    VARCHAR(150)  NOT NULL,
                    customer_mobile  VARCHAR(20)   NOT NULL,
                    invoice_number   VARCHAR(30)   NOT NULL UNIQUE,
                    cashier_username VARCHAR(100)  NOT NULL,
                    bill_date        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    subtotal         NUMERIC(12,2) NOT NULL,
                    discount_total   NUMERIC(12,2) NOT NULL DEFAULT 0,
                    grand_total      NUMERIC(12,2) NOT NULL,
                    amount_paid      NUMERIC(12,2) NOT NULL DEFAULT 0,
                    balance_due      NUMERIC(12,2) NOT NULL,
                    status           VARCHAR(20)   NOT NULL DEFAULT 'pending',
                    notes            VARCHAR(500),
                    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS credit_bill_items (
                    id              BIGINT         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    credit_bill_id  BIGINT         NOT NULL REFERENCES credit_bills(id) ON DELETE CASCADE,
                    product_id      BIGINT         NOT NULL REFERENCES products(id),
                    product_name    VARCHAR(150)   NOT NULL,
                    quantity        NUMERIC(12,3)  NOT NULL,
                    unit_price      NUMERIC(12,2)  NOT NULL,
                    line_total      NUMERIC(12,2)  NOT NULL,
                    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS idx_credit_bills_mobile ON credit_bills(customer_mobile)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_credit_bills_status ON credit_bills(status)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_credit_bill_items_bill ON credit_bill_items(credit_bill_id)")

            # ── Column migrations ─────────────────────────────────────────────
            # Add customer_name / customer_mobile to sales for optional display on receipt
            cur.execute("ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_name   VARCHAR(150)")
            cur.execute("ALTER TABLE sales ADD COLUMN IF NOT EXISTS customer_mobile VARCHAR(20)")

            # ── employees table ───────────────────────────────────────────────
            cur.execute("""
                CREATE TABLE IF NOT EXISTS employees (
                    id         BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    emp_code   VARCHAR(20)   NOT NULL UNIQUE,
                    full_name  VARCHAR(150)  NOT NULL,
                    phone      VARCHAR(20),
                    role       VARCHAR(100)  NOT NULL DEFAULT 'Staff',
                    daily_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
                    join_date  DATE          NOT NULL DEFAULT CURRENT_DATE,
                    active     BOOLEAN       NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            # Migration: rename monthly_salary -> daily_rate for existing tables
            cur.execute("""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns
                               WHERE table_name='employees' AND column_name='monthly_salary') THEN
                        ALTER TABLE employees RENAME COLUMN monthly_salary TO daily_rate;
                    END IF;
                END$$
            """)

            # ── attendance table ───────────────────────────────────────────────
            cur.execute("""
                CREATE TABLE IF NOT EXISTS attendance (
                    id          BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    employee_id BIGINT       NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
                    att_date    DATE         NOT NULL,
                    status      VARCHAR(20)  NOT NULL DEFAULT 'present',
                    marked_by   VARCHAR(100) NOT NULL,
                    notes       VARCHAR(300),
                    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (employee_id, att_date)
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(att_date)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_attendance_emp  ON attendance(employee_id)")

            # ── salary_payments table (multiple payouts per month allowed) ─────
            cur.execute("""
                CREATE TABLE IF NOT EXISTS salary_payments (
                    id          BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    employee_id BIGINT        NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
                    pay_month   VARCHAR(7)    NOT NULL,
                    amount_paid NUMERIC(12,2) NOT NULL,
                    paid_by     VARCHAR(100)  NOT NULL,
                    payment_type VARCHAR(20)  NOT NULL DEFAULT 'salary',
                    notes       VARCHAR(300),
                    paid_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            # Drop old UNIQUE constraint if it exists (was employee_id + pay_month)
            cur.execute("""
                DO $$
                DECLARE r RECORD;
                BEGIN
                    FOR r IN SELECT conname FROM pg_constraint
                             WHERE conrelid = 'salary_payments'::regclass
                               AND contype = 'u'
                    LOOP
                        EXECUTE 'ALTER TABLE salary_payments DROP CONSTRAINT ' || r.conname;
                    END LOOP;
                END$$
            """)
            # Add payment_type column if missing (for tables created before this migration)
            cur.execute("""
                ALTER TABLE salary_payments
                ADD COLUMN IF NOT EXISTS payment_type VARCHAR(20) NOT NULL DEFAULT 'salary'
            """)

            # ── advances table ─────────────────────────────────────────────────
            cur.execute("""
                CREATE TABLE IF NOT EXISTS advances (
                    id          BIGINT        PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    employee_id BIGINT        NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
                    amount      NUMERIC(12,2) NOT NULL,
                    given_on    DATE          NOT NULL DEFAULT CURRENT_DATE,
                    given_by    VARCHAR(100)  NOT NULL,
                    notes       VARCHAR(300),
                    recovered   BOOLEAN       NOT NULL DEFAULT FALSE,
                    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS idx_advances_emp ON advances(employee_id)")

        conn.commit()
        _db_ready = True
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

def _create_token(user_id: int, username: str, role: str) -> str:
    payload = {
        "sub": str(user_id),
        "username": username,
        "role": role,
        "exp": datetime.now(timezone.utc) + timedelta(hours=JWT_EXP_HOURS),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)


def _decode_token(token: str) -> dict:
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        return None, "Token has expired"
    except jwt.InvalidTokenError:
        return None, "Invalid token"


# ---------------------------------------------------------------------------
# Auth middleware helpers
# ---------------------------------------------------------------------------

def _get_token_from_request():
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return None, "Missing or invalid Authorization header"
    token = auth.split(" ", 1)[1]
    result = _decode_token(token)
    if isinstance(result, tuple):
        return None, result[1]
    return result, None


def require_auth():
    payload, err = _get_token_from_request()
    if err:
        return None, (jsonify({"detail": err}), 401)
    return payload, None


def require_admin():
    payload, err_resp = require_auth()
    if err_resp:
        return None, err_resp
    if payload.get("role") != "Admin":
        return None, (jsonify({"detail": "Admin role required"}), 403)
    return payload, None


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _product_to_dict(row: dict) -> dict:
    """Return a safe product dict. Booleans must be checked before numeric types."""
    d = dict(row)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
        elif isinstance(v, bool):
            d[k] = bool(v)          # keep True/False, do NOT cast to float
        elif isinstance(v, float):
            d[k] = float(v)
    return d


def _user_to_dict(row: dict) -> dict:
    d = dict(row)
    d.pop("password_hash", None)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
    return d


def _get_user_role(cur, user_id) -> str | None:
    cur.execute(
        """
        SELECT r.name FROM roles r
        JOIN user_roles ur ON ur.role_id = r.id
        WHERE ur.user_id = %s LIMIT 1
        """,
        (user_id,),
    )
    row = cur.fetchone()
    return row["name"] if row else None


def _assign_role(cur, user_id, role_name: str):
    cur.execute("SELECT id FROM roles WHERE name = %s", (role_name,))
    role = cur.fetchone()
    if not role:
        raise ValueError(f"Role '{role_name}' does not exist. Valid: {VALID_ROLES}")
    cur.execute("DELETE FROM user_roles WHERE user_id = %s", (user_id,))
    cur.execute(
        "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s)",
        (user_id, role["id"]),
    )


def _verify_password(plain: str, hashed: str) -> bool:
    if hashed.startswith(("scrypt:", "pbkdf2:", "sha256$")):
        return werkzeug_check(hashed, plain)
    return pwd_context.verify(plain, hashed)


def _needs_rehash(hashed: str) -> bool:
    return hashed.startswith(("scrypt:", "pbkdf2:", "sha256$"))


# ---------------------------------------------------------------------------
# Public routes
# ---------------------------------------------------------------------------


@app.get("/health")
@app.get("/api/health")
@app.get("/")
def health():
    try:
        conn = get_conn()
        conn.cursor().execute("SELECT 1")
        conn.close()
        return jsonify({"status": "healthy", "message": "Billing API is running", "db": "connected"})
    except Exception as e:
        return jsonify({"status": "unhealthy", "error": str(e)}), 500


@app.post("/login")
@app.post("/api/login")
def login():
    body = request.get_json(force=True, silent=True)
    if not body:
        import json
        try:
            body = json.loads(request.data.decode("utf-8"))
        except Exception:
            body = {}
    username = (body.get("username") or "").strip()
    password = (body.get("password") or "").strip()

    if not username or not password:
        return jsonify({"detail": "username and password are required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cur.fetchone()

        if not user or not _verify_password(password, user["password_hash"]):
            return jsonify({"detail": "Invalid username or password"}), 401
        if not user["active"]:
            return jsonify({"detail": "Account is disabled"}), 403

        # Migrate legacy Werkzeug hash → bcrypt on first successful login
        if _needs_rehash(user["password_hash"]):
            cur.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (pwd_context.hash(password), user["id"]),
            )
            conn.commit()

        role      = _get_user_role(cur, user["id"])
        token     = _create_token(user["id"], user["username"], role)
        user_data = _user_to_dict(user)
        user_data["role"] = role

        return jsonify({
            "message":    "Login successful",
            "token":      token,
            "token_type": "bearer",
            "user":       user_data,
        })
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Admin-only routes  (require Authorization: Bearer <token> with role=Admin)
# ---------------------------------------------------------------------------

@app.post("/register")
@app.post("/api/register")
def register():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    body = request.get_json(force=True, silent=True)
    if not body:
        import json
        try:
            body = json.loads(request.data.decode("utf-8"))
        except Exception:
            body = {}
    username  = (body.get("username") or "").strip()
    password  = (body.get("password") or "").strip()
    full_name = (body.get("full_name") or "").strip()
    role      = (body.get("role") or "").strip()

    if not username or not password or not full_name:
        return jsonify({"detail": "username, password, and full_name are required"}), 400
    if role not in VALID_ROLES:
        return jsonify({"detail": f"role must be one of {VALID_ROLES}"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE username = %s", (username,))
        if cur.fetchone():
            return jsonify({"detail": "Username already exists"}), 409
        cur.execute(
            "INSERT INTO users (username, password_hash, full_name) VALUES (%s, %s, %s) RETURNING *",
            (username, pwd_context.hash(password), full_name),
        )
        user_row = cur.fetchone()
        _assign_role(cur, user_row["id"], role)
        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = role
        return jsonify({"message": "User created successfully", "user": user}), 201
    except ValueError as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.get("/users")
@app.get("/api/users")
def list_users():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users ORDER BY id")
        users = []
        for row in cur.fetchall():
            u = _user_to_dict(row)
            u["role"] = _get_user_role(cur, row["id"])
            users.append(u)
        return jsonify({"users": users, "total": len(users)})
    finally:
        cur.close(); conn.close()


@app.put("/users/<int:user_id>")
@app.put("/api/users/<int:user_id>")
def update_user(user_id: int):
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE id = %s", (user_id,))
        if not cur.fetchone():
            return jsonify({"detail": "User not found"}), 404

        body = request.get_json(force=True, silent=True)
        if not body:
            import json
            try:
                body = json.loads(request.data.decode("utf-8"))
            except Exception:
                body = {}
        fields, values = [], []

        full_name = (body.get("full_name") or "").strip()
        username  = (body.get("username") or "").strip()
        password  = (body.get("password") or "").strip()
        active    = body.get("active")
        new_role  = (body.get("role") or "").strip()

        if full_name:
            fields.append("full_name = %s"); values.append(full_name)
        if username:
            fields.append("username = %s"); values.append(username)
        if password:
            fields.append("password_hash = %s"); values.append(pwd_context.hash(password))
        if active is not None:
            fields.append("active = %s"); values.append(active)

        if fields:
            fields.append("updated_at = NOW()")
            values.append(user_id)
            cur.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
            user_row = cur.fetchone()
        else:
            cur.execute("SELECT * FROM users WHERE id = %s", (user_id,))
            user_row = cur.fetchone()

        if new_role:
            if new_role not in VALID_ROLES:
                return jsonify({"detail": f"role must be one of {VALID_ROLES}"}), 400
            _assign_role(cur, user_id, new_role)

        if not fields and not new_role:
            return jsonify({"detail": "No valid fields provided to update"}), 400

        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = _get_user_role(cur, user_id)
        return jsonify({"message": "User updated successfully", "user": user})
    except ValueError as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Category routes (any logged-in user)
# ---------------------------------------------------------------------------

@app.get("/categories")
@app.get("/api/categories")
def list_categories():
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM categories WHERE active = TRUE ORDER BY name")
        categories = []
        for row in cur.fetchall():
            d = dict(row)
            for k, v in d.items():
                if isinstance(v, datetime):
                    d[k] = v.isoformat()
            categories.append(d)
        return jsonify({"categories": categories, "total": len(categories)})
    finally:
        cur.close(); conn.close()


@app.post("/categories")
@app.post("/api/categories")
def create_category():
    body = request.get_json(silent=True) or {}

    name        = (body.get("name") or "").strip()
    description = (body.get("description") or "").strip()
    active      = body.get("active", True)

    if not name:
        return jsonify({"detail": "Category name is required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM categories WHERE name = %s", (name,))
        if cur.fetchone():
            return jsonify({"detail": "Category name already exists"}), 409

        cur.execute(
            """
            INSERT INTO categories (name, description, active)
            VALUES (%s, %s, %s)
            RETURNING *
            """,
            (name, description or None, active),
        )
        category_row = cur.fetchone()
        conn.commit()
        d = dict(category_row)
        for k, v in d.items():
            if isinstance(v, datetime):
                d[k] = v.isoformat()
        return jsonify({"message": "Category created successfully", "category": d}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.put("/categories/<int:category_id>")
@app.put("/api/categories/<int:category_id>")
def update_category(category_id: int):
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM categories WHERE id = %s", (category_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Category not found"}), 404

        body = request.get_json(silent=True) or {}
        fields, values = [], []

        name        = (body.get("name") or "").strip()
        description = (body.get("description") or "").strip()
        active      = body.get("active")

        if name:
            fields.append("name = %s"); values.append(name)
        if description:
            fields.append("description = %s"); values.append(description)
        if active is not None:
            fields.append("active = %s"); values.append(active)

        if fields:
            fields.append("updated_at = NOW()")
            values.append(category_id)
            cur.execute(f"UPDATE categories SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
            category_row = cur.fetchone()
            conn.commit()
            d = dict(category_row)
            for k, v in d.items():
                if isinstance(v, datetime):
                    d[k] = v.isoformat()
            return jsonify({"message": "Category updated successfully", "category": d})
        else:
            return jsonify({"detail": "No valid fields provided to update"}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.delete("/categories/<int:category_id>")
@app.delete("/api/categories/<int:category_id>")
def delete_category(category_id: int):
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM categories WHERE id = %s", (category_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Category not found"}), 404

        # Check if category is in use
        cur.execute("SELECT id FROM products WHERE category_id = %s LIMIT 1", (category_id,))
        if cur.fetchone():
            return jsonify({"detail": "Cannot delete category that is in use by products"}), 400

        cur.execute("DELETE FROM categories WHERE id = %s", (category_id,))
        conn.commit()
        return jsonify({"message": "Category deleted successfully"})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Product routes (any logged-in user)
# ---------------------------------------------------------------------------

@app.get("/products")
@app.get("/api/products")
def list_products():
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM products ORDER BY name")
        products = []
        for row in cur.fetchall():
            products.append(_product_to_dict(row))
        return jsonify({"products": products, "total": len(products)})
    finally:
        cur.close(); conn.close()


@app.post("/products")
@app.post("/api/products")
def create_product():
    body = request.get_json(silent=True) or {}

    name                = (body.get("name") or "").strip()
    barcode             = (body.get("barcode") or "").strip()
    brand               = (body.get("brand") or "").strip()
    category_id         = body.get("category_id")
    subcategory         = (body.get("subcategory") or "").strip()
    unit                = (body.get("unit") or "").strip()
    purchase_price      = body.get("purchase_price", 0)
    mrp                 = body.get("mrp", 0)
    selling_price       = body.get("selling_price", 0)
    gst_percentage      = body.get("gst_percentage", 0)
    track_stock         = body.get("track_stock", True)
    current_stock       = body.get("current_stock")
    minimum_stock_level = body.get("minimum_stock_level")
    quick_sale_enabled  = body.get("quick_sale_enabled", False)
    active              = body.get("active", True)

    if not name:
        return jsonify({"detail": "Product name is required"}), 400
    if not category_id:
        return jsonify({"detail": "Category is required"}), 400
    if not unit:
        return jsonify({"detail": "Unit is required"}), 400
    if track_stock and (current_stock is None or current_stock == ""):
        return jsonify({"detail": "Current stock is required when track_stock is enabled"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        if barcode:
            cur.execute("SELECT id FROM products WHERE barcode = %s", (barcode,))
            if cur.fetchone():
                return jsonify({"detail": "Barcode already exists"}), 409

        cur.execute(
            """
            INSERT INTO products (name, barcode, brand, category_id, subcategory, unit, purchase_price, mrp, selling_price, gst_percentage, track_stock, current_stock, minimum_stock_level, quick_sale_enabled, active)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (name, barcode or None, brand or None, category_id, subcategory or None, unit, purchase_price, mrp, selling_price, gst_percentage, track_stock, current_stock if track_stock else None, minimum_stock_level if track_stock else None, quick_sale_enabled, active),
        )
        product_row = cur.fetchone()
        conn.commit()
        return jsonify({"message": "Product created successfully", "product": _product_to_dict(product_row)}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.put("/products/<int:product_id>")
@app.put("/api/products/<int:product_id>")
def update_product(product_id: int):
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM products WHERE id = %s", (product_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Product not found"}), 404

        body = request.get_json(silent=True) or {}
        fields, values = [], []

        name                = (body.get("name") or "").strip()
        barcode             = (body.get("barcode") or "").strip()
        brand               = (body.get("brand") or "").strip()
        category_id         = body.get("category_id")
        subcategory         = (body.get("subcategory") or "").strip()
        unit                = (body.get("unit") or "").strip()
        purchase_price      = body.get("purchase_price")
        mrp                 = body.get("mrp")
        selling_price       = body.get("selling_price")
        gst_percentage      = body.get("gst_percentage")
        track_stock         = body.get("track_stock")
        current_stock       = body.get("current_stock")
        minimum_stock_level = body.get("minimum_stock_level")
        quick_sale_enabled  = body.get("quick_sale_enabled")
        active              = body.get("active")

        if name:
            fields.append("name = %s"); values.append(name)
        if barcode:
            fields.append("barcode = %s"); values.append(barcode)
        if brand:
            fields.append("brand = %s"); values.append(brand)
        if category_id:
            fields.append("category_id = %s"); values.append(category_id)
        if subcategory:
            fields.append("subcategory = %s"); values.append(subcategory)
        if unit:
            fields.append("unit = %s"); values.append(unit)
        if purchase_price is not None:
            fields.append("purchase_price = %s"); values.append(purchase_price)
        if mrp is not None:
            fields.append("mrp = %s"); values.append(mrp)
        if selling_price is not None:
            fields.append("selling_price = %s"); values.append(selling_price)
        if gst_percentage is not None:
            fields.append("gst_percentage = %s"); values.append(gst_percentage)
        if track_stock is not None:
            fields.append("track_stock = %s"); values.append(track_stock)
        if current_stock is not None:
            fields.append("current_stock = %s"); values.append(current_stock)
        if minimum_stock_level is not None:
            fields.append("minimum_stock_level = %s"); values.append(minimum_stock_level)
        if quick_sale_enabled is not None:
            fields.append("quick_sale_enabled = %s"); values.append(quick_sale_enabled)
        if active is not None:
            fields.append("active = %s"); values.append(active)

        if fields:
            fields.append("updated_at = NOW()")
            values.append(product_id)
            cur.execute(f"UPDATE products SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
            product_row = cur.fetchone()
            conn.commit()
            return jsonify({"message": "Product updated successfully", "product": _product_to_dict(product_row)})
        else:
            return jsonify({"detail": "No valid fields provided to update"}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.delete("/products/<int:product_id>")
@app.delete("/api/products/<int:product_id>")
def delete_product(product_id: int):
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM products WHERE id = %s", (product_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Product not found"}), 404

        cur.execute("DELETE FROM products WHERE id = %s", (product_id,))
        conn.commit()
        return jsonify({"message": "Product deleted successfully"})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing helpers
# ---------------------------------------------------------------------------

def _row_to_dict(row):
    """Convert DB row to dict. Booleans checked before numeric to avoid True→1.0."""
    d = dict(row)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
        elif isinstance(v, bool):
            d[k] = bool(v)          # keep True/False, do NOT cast to float
        elif hasattr(v, '__float__'):
            d[k] = float(v)
    return d


def _generate_invoice_number(cur):
    """Generate invoice number like INV-20260916-0001."""
    from datetime import date
    today = date.today().strftime("%Y%m%d")
    cur.execute(
        "SELECT COUNT(*) as cnt FROM sales WHERE invoice_number LIKE %s",
        (f"INV-{today}-%",)
    )
    row = cur.fetchone()
    seq = int(row["cnt"]) + 1
    return f"INV-{today}-{seq:04d}"


def _generate_hold_reference(cur):
    """Generate hold reference like HOLD-20260916-001."""
    from datetime import date
    today = date.today().strftime("%Y%m%d")
    cur.execute(
        "SELECT COUNT(*) as cnt FROM held_sales WHERE hold_reference LIKE %s",
        (f"HOLD-{today}-%",)
    )
    row = cur.fetchone()
    seq = int(row["cnt"]) + 1
    return f"HOLD-{today}-{seq:03d}"


# ---------------------------------------------------------------------------
# Billing — Checkout (POST /api/billing/checkout)
# ---------------------------------------------------------------------------

@app.post("/billing/checkout")
@app.post("/api/billing/checkout")
def checkout():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    body = request.get_json(silent=True) or {}
    items            = body.get("items", [])
    discount_total   = float(body.get("discount_total", 0))
    payment_method   = (body.get("payment_method") or "cash").strip()
    amount_tendered  = body.get("amount_tendered")
    customer_name    = (body.get("customer_name") or "").strip() or None
    customer_mobile  = (body.get("customer_mobile") or "").strip() or None
    cashier_username = payload.get("username", "unknown")

    if not items:
        return jsonify({"detail": "Cart is empty"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        # Validate products and compute totals
        subtotal  = 0.0
        tax_total = 0.0
        enriched  = []
        for item in items:
            pid = item.get("product_id") or item.get("id")
            qty = float(item.get("quantity", 1))
            cur.execute("SELECT * FROM products WHERE id = %s AND active = TRUE", (pid,))
            product = cur.fetchone()
            if not product:
                return jsonify({"detail": f"Product id={pid} not found or inactive"}), 400

            unit_price      = float(product["selling_price"])
            gst_pct         = float(product["gst_percentage"])
            discount_amount = float(item.get("discount_amount", 0))
            tax_amount      = round((unit_price * qty - discount_amount) * gst_pct / 100, 2)
            line_total      = round(unit_price * qty - discount_amount + tax_amount, 2)
            subtotal  += unit_price * qty
            tax_total += tax_amount
            enriched.append({
                "product_id":      pid,
                "product_name":    product["name"],
                "barcode":         product["barcode"],
                "quantity":        qty,
                "unit_price":      unit_price,
                "discount_amount": discount_amount,
                "tax_amount":      tax_amount,
                "line_total":      line_total,
                "track_stock":     product.get("track_stock", True),   # default True if column missing
                "current_stock":   product.get("current_stock"),
            })

        grand_before_round = subtotal - discount_total + tax_total
        grand_total        = round(grand_before_round)
        round_off          = round(grand_total - grand_before_round, 2)
        change_amount      = round(float(amount_tendered or grand_total) - grand_total, 2) if amount_tendered else 0.0

        invoice_number = _generate_invoice_number(cur)

        # Insert sale — sale_time + optional customer fields
        cur.execute(
            """
            INSERT INTO sales (invoice_number, cashier_username, sale_time, subtotal, discount_total, tax_total,
                               round_off, grand_total, payment_method, amount_tendered, change_amount,
                               customer_name, customer_mobile, status)
            VALUES (%s, %s, NOW(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 'completed')
            RETURNING *
            """,
            (invoice_number, cashier_username, round(subtotal, 2), round(discount_total, 2),
             round(tax_total, 2), round_off, grand_total, payment_method,
             float(amount_tendered) if amount_tendered else None, change_amount,
             customer_name, customer_mobile),
        )
        sale = cur.fetchone()
        sale_id = sale["id"]

        # Insert sale items + deduct stock
        for item in enriched:
            cur.execute(
                """
                INSERT INTO sale_items (sale_id, product_id, product_name, barcode, quantity, unit_price, discount_amount, tax_amount, line_total)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (sale_id, item["product_id"], item["product_name"], item["barcode"],
                 item["quantity"], item["unit_price"], item["discount_amount"],
                 item["tax_amount"], item["line_total"]),
            )
            # Only deduct stock for products where track_stock = TRUE
            # Non-stockable items (Tea, Coffee, Juice, etc.) are skipped entirely
            if item.get("track_stock", True) is True and item.get("current_stock") is not None:
                stock_before = float(item["current_stock"])
                stock_after  = max(0.0, stock_before - item["quantity"])
                cur.execute(
                    "UPDATE products SET current_stock = %s, updated_at = NOW() WHERE id = %s",
                    (stock_after, item["product_id"]),
                )
                cur.execute(
                    """
                    INSERT INTO inventory_transactions (product_id, transaction_type, quantity_change, stock_before, stock_after, reference_type, reference_id, remarks)
                    VALUES (%s, 'sale', %s, %s, %s, 'sale', %s, %s)
                    """,
                    (item["product_id"], -item["quantity"], stock_before, stock_after,
                     invoice_number, f"Sale: {invoice_number}"),
                )
            # If track_stock = FALSE → skip stock update and inventory log entirely

        conn.commit()
        return jsonify({
            "message":        "Sale completed successfully",
            "invoice_number": invoice_number,
            "sale_id":        sale_id,
            "grand_total":    grand_total,
            "change_amount":  change_amount,
            "sale":           _row_to_dict(sale),
        }), 201

    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing — Get sale receipt (GET /api/billing/receipt/<invoice_number>)
# ---------------------------------------------------------------------------

@app.get("/billing/receipt/<invoice_number>")
@app.get("/api/billing/receipt/<invoice_number>")
def get_receipt(invoice_number):
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM sales WHERE invoice_number = %s", (invoice_number,))
        sale = cur.fetchone()
        if not sale:
            return jsonify({"detail": "Invoice not found"}), 404
        cur.execute("SELECT * FROM sale_items WHERE sale_id = %s ORDER BY id", (sale["id"],))
        items = [_row_to_dict(r) for r in cur.fetchall()]
        return jsonify({"sale": _row_to_dict(sale), "items": items})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing — Hold sale (POST /api/billing/hold)
# ---------------------------------------------------------------------------

@app.post("/billing/hold")
@app.post("/api/billing/hold")
def hold_sale():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    body = request.get_json(silent=True) or {}
    items            = body.get("items", [])
    discount_total   = float(body.get("discount_total", 0))
    cashier_username = payload.get("username", "unknown")

    if not items:
        return jsonify({"detail": "Cart is empty"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        subtotal  = 0.0
        tax_total = 0.0
        enriched  = []
        for item in items:
            pid = item.get("product_id") or item.get("id")
            qty = float(item.get("quantity", 1))
            cur.execute("SELECT * FROM products WHERE id = %s", (pid,))
            product = cur.fetchone()
            if not product:
                return jsonify({"detail": f"Product id={pid} not found"}), 400
            unit_price      = float(product["selling_price"])
            gst_pct         = float(product["gst_percentage"])
            discount_amount = float(item.get("discount_amount", 0))
            tax_amount      = round((unit_price * qty - discount_amount) * gst_pct / 100, 2)
            line_total      = round(unit_price * qty - discount_amount + tax_amount, 2)
            subtotal  += unit_price * qty
            tax_total += tax_amount
            enriched.append({
                "product_id":      pid,
                "product_name":    product["name"],
                "quantity":        qty,
                "unit_price":      unit_price,
                "discount_amount": discount_amount,
                "tax_amount":      tax_amount,
                "line_total":      line_total,
            })

        grand_total      = round(subtotal - discount_total + tax_total, 2)
        hold_reference   = _generate_hold_reference(cur)

        cur.execute(
            """
            INSERT INTO held_sales (hold_reference, cashier_username, subtotal, discount_total, tax_total, grand_total)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (hold_reference, cashier_username, round(subtotal, 2),
             round(discount_total, 2), round(tax_total, 2), grand_total),
        )
        held = cur.fetchone()
        held_id = held["id"]

        for item in enriched:
            cur.execute(
                """
                INSERT INTO held_sale_items (held_sale_id, product_id, product_name, quantity, unit_price, discount_amount, tax_amount, line_total)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (held_id, item["product_id"], item["product_name"], item["quantity"],
                 item["unit_price"], item["discount_amount"], item["tax_amount"], item["line_total"]),
            )

        conn.commit()
        return jsonify({
            "message":        "Sale held successfully",
            "hold_reference": hold_reference,
            "held_sale":      _row_to_dict(held),
        }), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing — List held sales (GET /api/billing/held)
# ---------------------------------------------------------------------------

@app.get("/billing/held")
@app.get("/api/billing/held")
def list_held_sales():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM held_sales ORDER BY created_at DESC")
        held_sales = [_row_to_dict(r) for r in cur.fetchall()]
        return jsonify({"held_sales": held_sales, "total": len(held_sales)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing — Retrieve held sale (GET /api/billing/held/<ref>)
# ---------------------------------------------------------------------------

@app.get("/billing/held/<string:hold_reference>")
@app.get("/api/billing/held/<string:hold_reference>")
def get_held_sale(hold_reference):
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM held_sales WHERE hold_reference = %s", (hold_reference,))
        held = cur.fetchone()
        if not held:
            return jsonify({"detail": "Held sale not found"}), 404
        cur.execute("SELECT * FROM held_sale_items WHERE held_sale_id = %s ORDER BY id", (held["id"],))
        items = [_row_to_dict(r) for r in cur.fetchall()]
        return jsonify({"held_sale": _row_to_dict(held), "items": items})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Billing — Delete (release) held sale (DELETE /api/billing/held/<ref>)
# ---------------------------------------------------------------------------

@app.delete("/billing/held/<string:hold_reference>")
@app.delete("/api/billing/held/<string:hold_reference>")
def delete_held_sale(hold_reference):
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM held_sales WHERE hold_reference = %s", (hold_reference,))
        held = cur.fetchone()
        if not held:
            return jsonify({"detail": "Held sale not found"}), 404
        cur.execute("DELETE FROM held_sales WHERE id = %s", (held["id"],))
        conn.commit()
        return jsonify({"message": "Held sale deleted"})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Sales history (GET /api/billing/sales)
# ---------------------------------------------------------------------------

@app.get("/billing/sales")
@app.get("/api/billing/sales")
def list_sales():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM sales ORDER BY sale_time DESC LIMIT 100")
        sales = [_row_to_dict(r) for r in cur.fetchall()]
        return jsonify({"sales": sales, "total": len(sales)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Category-wise sales stats (GET /api/billing/stats/categories)
# ---------------------------------------------------------------------------

@app.get("/billing/stats/categories")
@app.get("/api/billing/stats/categories")
def category_sales_stats():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    # Optional date range filters: ?date_from=YYYY-MM-DD&date_to=YYYY-MM-DD
    date_from = request.args.get("date_from")  # inclusive start
    date_to   = request.args.get("date_to")    # inclusive end

    # Build a sale_time filter clause used in all three queries
    # We cast to DATE so the comparison is day-level, not timestamp-level
    date_conditions = []
    date_params: list = []
    if date_from:
        date_conditions.append("s.sale_time::DATE >= %s")
        date_params.append(date_from)
    if date_to:
        date_conditions.append("s.sale_time::DATE <= %s")
        date_params.append(date_to)
    date_where = ("AND " + " AND ".join(date_conditions)) if date_conditions else ""

    # Same for summary (no alias "s")
    summary_conditions = []
    summary_params: list = []
    if date_from:
        summary_conditions.append("sale_time::DATE >= %s")
        summary_params.append(date_from)
    if date_to:
        summary_conditions.append("sale_time::DATE <= %s")
        summary_params.append(date_to)
    summary_where = ("AND " + " AND ".join(summary_conditions)) if summary_conditions else ""

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        # Category-wise qty + revenue filtered by date
        cur.execute(f"""
            SELECT
                c.id                                          AS category_id,
                c.name                                        AS category_name,
                COUNT(DISTINCT si.sale_id)                    AS total_orders,
                COALESCE(SUM(si.quantity),  0)                AS total_qty,
                COALESCE(SUM(si.line_total), 0)               AS total_revenue
            FROM categories c
            LEFT JOIN products p  ON p.category_id = c.id
            LEFT JOIN sale_items si ON si.product_id = p.id
            LEFT JOIN sales s       ON s.id = si.sale_id {date_where}
            GROUP BY c.id, c.name
            ORDER BY total_qty DESC
        """, date_params)
        stats = []
        for r in cur.fetchall():
            stats.append({
                "category_id":   r["category_id"],
                "category_name": r["category_name"],
                "total_orders":  int(r["total_orders"]),
                "total_qty":     float(r["total_qty"]),
                "total_revenue": float(r["total_revenue"]),
            })

        # Top 10 products filtered by date
        cur.execute(f"""
            SELECT
                p.name                          AS product_name,
                c.name                          AS category_name,
                COALESCE(SUM(si.quantity),  0)  AS total_qty,
                COALESCE(SUM(si.line_total), 0) AS total_revenue
            FROM sale_items si
            JOIN products  p ON p.id = si.product_id
            JOIN categories c ON c.id = p.category_id
            JOIN sales      s ON s.id = si.sale_id {date_where}
            GROUP BY p.id, p.name, c.name
            ORDER BY total_qty DESC
            LIMIT 10
        """, date_params)
        top_products = []
        for r in cur.fetchall():
            top_products.append({
                "product_name":  r["product_name"],
                "category_name": r["category_name"],
                "total_qty":     float(r["total_qty"]),
                "total_revenue": float(r["total_revenue"]),
            })

        # Overall summary filtered by date
        cur.execute(f"""
            SELECT
                COUNT(*)                        AS total_sales,
                COALESCE(SUM(grand_total), 0)   AS total_revenue,
                COALESCE(SUM(tax_total),   0)   AS total_tax
            FROM sales
            WHERE status = 'completed' {summary_where}
        """, summary_params)
        summary_row = cur.fetchone()
        summary = {
            "total_sales":   int(summary_row["total_sales"]),
            "total_revenue": float(summary_row["total_revenue"]),
            "total_tax":     float(summary_row["total_tax"]),
        }

        return jsonify({
            "summary":      summary,
            "by_category":  stats,
            "top_products": top_products,
            "date_from":    date_from,
            "date_to":      date_to,
        })
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Credit Bills — CREATE  (POST /api/credit-bills)
# ---------------------------------------------------------------------------

def _credit_invoice_number(cur):
    from datetime import date
    today = date.today().strftime("%Y%m%d")
    cur.execute("SELECT COUNT(*) AS cnt FROM credit_bills WHERE invoice_number LIKE %s", (f"CRD-{today}-%",))
    cnt = int(cur.fetchone()["cnt"]) + 1
    return f"CRD-{today}-{cnt:04d}"


@app.post("/credit-bills")
@app.post("/api/credit-bills")
def create_credit_bill():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    body             = request.get_json(silent=True) or {}
    customer_name    = (body.get("customer_name") or "").strip()
    customer_mobile  = (body.get("customer_mobile") or "").strip()
    items            = body.get("items", [])
    discount_total   = float(body.get("discount_total", 0))
    amount_paid      = float(body.get("amount_paid", 0))
    notes            = (body.get("notes") or "").strip() or None
    cashier_username = payload.get("username", "unknown")

    if not customer_name:
        return jsonify({"detail": "Customer name is required"}), 400
    if not customer_mobile:
        return jsonify({"detail": "Customer mobile number is required"}), 400
    if not items:
        return jsonify({"detail": "Cart is empty"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        subtotal = 0.0
        enriched = []
        for item in items:
            pid = item.get("product_id") or item.get("id")
            qty = float(item.get("quantity", 1))
            cur.execute("SELECT * FROM products WHERE id = %s", (pid,))
            product = cur.fetchone()
            if not product:
                return jsonify({"detail": f"Product id={pid} not found"}), 400
            unit_price = float(product["selling_price"])
            line_total = round(unit_price * qty, 2)
            subtotal  += unit_price * qty
            enriched.append({
                "product_id":   pid,
                "product_name": product["name"],
                "quantity":     qty,
                "unit_price":   unit_price,
                "line_total":   line_total,
            })

        grand_total  = round(subtotal - discount_total, 2)
        balance_due  = round(grand_total - amount_paid, 2)
        status       = "paid" if balance_due <= 0 else "pending"
        invoice_number = _credit_invoice_number(cur)

        cur.execute(
            """
            INSERT INTO credit_bills
              (customer_name, customer_mobile, invoice_number, cashier_username,
               bill_date, subtotal, discount_total, grand_total,
               amount_paid, balance_due, status, notes)
            VALUES (%s, %s, %s, %s, NOW(), %s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (customer_name, customer_mobile, invoice_number, cashier_username,
             round(subtotal, 2), round(discount_total, 2), grand_total,
             round(amount_paid, 2), balance_due, status, notes),
        )
        bill = dict(cur.fetchone())
        bill_id = bill["id"]

        for item in enriched:
            cur.execute(
                """
                INSERT INTO credit_bill_items
                  (credit_bill_id, product_id, product_name, quantity, unit_price, line_total)
                VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (bill_id, item["product_id"], item["product_name"],
                 item["quantity"], item["unit_price"], item["line_total"]),
            )

        conn.commit()
        return jsonify({"message": "Credit bill created", "credit_bill": bill, "invoice_number": invoice_number}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 500
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Credit Bills — LIST  (GET /api/credit-bills)
# ---------------------------------------------------------------------------

@app.get("/credit-bills")
@app.get("/api/credit-bills")
def list_credit_bills():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    status_filter = request.args.get("status")     # pending | paid | all
    mobile_filter = request.args.get("mobile")
    date_from     = request.args.get("date_from")
    date_to       = request.args.get("date_to")

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        conds  = []
        params = []
        if status_filter and status_filter != "all":
            conds.append("status = %s"); params.append(status_filter)
        if mobile_filter:
            conds.append("customer_mobile LIKE %s"); params.append(f"%{mobile_filter}%")
        if date_from:
            conds.append("bill_date::DATE >= %s"); params.append(date_from)
        if date_to:
            conds.append("bill_date::DATE <= %s"); params.append(date_to)

        where = ("WHERE " + " AND ".join(conds)) if conds else ""
        cur.execute(f"SELECT * FROM credit_bills {where} ORDER BY bill_date DESC", params)
        bills = [_row_to_dict(r) for r in cur.fetchall()]

        # Attach items for each bill
        for bill in bills:
            cur.execute("SELECT * FROM credit_bill_items WHERE credit_bill_id = %s ORDER BY id", (bill["id"],))
            bill["items"] = [_row_to_dict(r) for r in cur.fetchall()]

        # Summary
        cur.execute(f"""
            SELECT
                COUNT(*)                              AS total_bills,
                COALESCE(SUM(grand_total), 0)         AS total_amount,
                COALESCE(SUM(balance_due), 0)         AS total_due,
                COALESCE(SUM(amount_paid), 0)         AS total_collected
            FROM credit_bills {where}
        """, params)
        s = cur.fetchone()
        summary = {
            "total_bills":     int(s["total_bills"]),
            "total_amount":    float(s["total_amount"]),
            "total_due":       float(s["total_due"]),
            "total_collected": float(s["total_collected"]),
        }

        return jsonify({"credit_bills": bills, "summary": summary, "total": len(bills)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Credit Bills — MARK PAYMENT  (POST /api/credit-bills/<id>/pay)
# ---------------------------------------------------------------------------

@app.post("/credit-bills/<int:bill_id>/pay")
@app.post("/api/credit-bills/<int:bill_id>/pay")
def pay_credit_bill(bill_id: int):
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    body       = request.get_json(silent=True) or {}
    pay_amount = float(body.get("amount", 0))

    if pay_amount <= 0:
        return jsonify({"detail": "Payment amount must be > 0"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM credit_bills WHERE id = %s", (bill_id,))
        bill = cur.fetchone()
        if not bill:
            return jsonify({"detail": "Credit bill not found"}), 404

        new_paid    = round(float(bill["amount_paid"]) + pay_amount, 2)
        new_balance = round(float(bill["grand_total"]) - new_paid, 2)
        new_status  = "paid" if new_balance <= 0 else "partial"

        cur.execute(
            """
            UPDATE credit_bills
               SET amount_paid = %s, balance_due = %s, status = %s, updated_at = NOW()
             WHERE id = %s
            RETURNING *
            """,
            (new_paid, max(0, new_balance), new_status, bill_id),
        )
        updated = _row_to_dict(cur.fetchone())
        conn.commit()
        return jsonify({"message": "Payment recorded", "credit_bill": updated})
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 500
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Credit Bills — DELETE  (DELETE /api/credit-bills/<id>)
# ---------------------------------------------------------------------------

@app.delete("/credit-bills/<int:bill_id>")
@app.delete("/api/credit-bills/<int:bill_id>")
def delete_credit_bill(bill_id: int):
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM credit_bills WHERE id = %s", (bill_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Credit bill not found"}), 404
        cur.execute("DELETE FROM credit_bills WHERE id = %s", (bill_id,))
        conn.commit()
        return jsonify({"message": "Credit bill deleted"})
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 500
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Stock Alerts — low stock items  (GET /api/stock/alerts)
# ---------------------------------------------------------------------------

@app.get("/stock/alerts")
@app.get("/api/stock/alerts")
def stock_alerts():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        # Out of stock: track_stock=true, current_stock = 0 (or null)
        cur.execute("""
            SELECT
                p.id, p.name, p.unit, p.current_stock, p.minimum_stock_level,
                c.name AS category_name
            FROM products p
            LEFT JOIN categories c ON c.id = p.category_id
            WHERE p.active = TRUE
              AND p.track_stock = TRUE
              AND (p.current_stock IS NULL OR p.current_stock <= 0)
            ORDER BY c.name, p.name
        """)
        out_of_stock = []
        for r in cur.fetchall():
            out_of_stock.append({
                "id":                  r["id"],
                "name":                r["name"],
                "unit":                r["unit"],
                "current_stock":       float(r["current_stock"] or 0),
                "minimum_stock_level": float(r["minimum_stock_level"] or 0),
                "category_name":       r["category_name"] or "Uncategorised",
            })

        # Low stock: track_stock=true, current_stock > 0 but <= minimum_stock_level
        cur.execute("""
            SELECT
                p.id, p.name, p.unit, p.current_stock, p.minimum_stock_level,
                c.name AS category_name
            FROM products p
            LEFT JOIN categories c ON c.id = p.category_id
            WHERE p.active = TRUE
              AND p.track_stock = TRUE
              AND p.current_stock  > 0
              AND p.minimum_stock_level IS NOT NULL
              AND p.minimum_stock_level > 0
              AND p.current_stock <= p.minimum_stock_level
            ORDER BY (p.current_stock / p.minimum_stock_level) ASC, p.name
        """)
        low_stock = []
        for r in cur.fetchall():
            low_stock.append({
                "id":                  r["id"],
                "name":                r["name"],
                "unit":                r["unit"],
                "current_stock":       float(r["current_stock"]),
                "minimum_stock_level": float(r["minimum_stock_level"]),
                "category_name":       r["category_name"] or "Uncategorised",
            })

        # Summary counts
        cur.execute("""
            SELECT COUNT(*) AS total_tracked
            FROM products
            WHERE active = TRUE AND track_stock = TRUE
        """)
        total_tracked = int(cur.fetchone()["total_tracked"])

        return jsonify({
            "out_of_stock":  out_of_stock,
            "low_stock":     low_stock,
            "total_tracked": total_tracked,
            "total_alerts":  len(out_of_stock) + len(low_stock),
        })
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Employees — helper
# ---------------------------------------------------------------------------

def _emp_to_dict(row: dict) -> dict:
    d = dict(row)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
        elif hasattr(v, 'isoformat'):       # date objects
            d[k] = v.isoformat()
        elif isinstance(v, bool):
            d[k] = bool(v)
        elif isinstance(v, float):
            d[k] = float(v)
    return d


# ---------------------------------------------------------------------------
# Employees — LIST  (GET /api/employees)   — any logged-in user
# ---------------------------------------------------------------------------

@app.get("/employees")
@app.get("/api/employees")
def list_employees():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM employees ORDER BY full_name")
        employees = [_emp_to_dict(r) for r in cur.fetchall()]
        return jsonify({"employees": employees, "total": len(employees)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Employees — CREATE  (POST /api/employees)   — Admin only
# ---------------------------------------------------------------------------

@app.post("/employees")
@app.post("/api/employees")
def create_employee():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    body       = request.get_json(silent=True) or {}
    full_name  = (body.get("full_name") or "").strip()
    emp_code   = (body.get("emp_code") or "").strip()
    phone      = (body.get("phone") or "").strip()
    role       = (body.get("role") or "Staff").strip()
    daily_rate = float(body.get("daily_rate", 0))
    join_date  = (body.get("join_date") or "").strip() or None

    if not full_name:
        return jsonify({"detail": "full_name is required"}), 400
    if not emp_code:
        return jsonify({"detail": "emp_code is required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM employees WHERE emp_code = %s", (emp_code,))
        if cur.fetchone():
            return jsonify({"detail": "Employee code already exists"}), 409
        cur.execute(
            """
            INSERT INTO employees (emp_code, full_name, phone, role, daily_rate, join_date)
            VALUES (%s, %s, %s, %s, %s, COALESCE(%s::DATE, CURRENT_DATE))
            RETURNING *
            """,
            (emp_code, full_name, phone or None, role, daily_rate, join_date),
        )
        emp = cur.fetchone()
        conn.commit()
        return jsonify({"message": "Employee created", "employee": _emp_to_dict(emp)}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Employees — UPDATE  (PUT /api/employees/<id>)   — Admin only
# ---------------------------------------------------------------------------

@app.put("/employees/<int:emp_id>")
@app.put("/api/employees/<int:emp_id>")
def update_employee(emp_id: int):
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM employees WHERE id = %s", (emp_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Employee not found"}), 404

        body = request.get_json(silent=True) or {}
        fields, values = [], []

        full_name  = (body.get("full_name") or "").strip()
        phone      = body.get("phone")
        role       = (body.get("role") or "").strip()
        daily_rate = body.get("daily_rate")
        join_date  = body.get("join_date")
        active     = body.get("active")

        if full_name:
            fields.append("full_name = %s"); values.append(full_name)
        if phone is not None:
            fields.append("phone = %s"); values.append(phone or None)
        if role:
            fields.append("role = %s"); values.append(role)
        if daily_rate is not None:
            fields.append("daily_rate = %s"); values.append(float(daily_rate))
        if join_date:
            fields.append("join_date = %s"); values.append(join_date)
        if active is not None:
            fields.append("active = %s"); values.append(active)

        if not fields:
            return jsonify({"detail": "No fields to update"}), 400

        fields.append("updated_at = NOW()")
        values.append(emp_id)
        cur.execute(f"UPDATE employees SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
        emp = cur.fetchone()
        conn.commit()
        return jsonify({"message": "Employee updated", "employee": _emp_to_dict(emp)})
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Attendance — MARK / UPSERT  (POST /api/attendance)
# Cashier (or Admin) can mark attendance for any employee for a given date.
# Status: present | absent | half_day | leave
# ---------------------------------------------------------------------------

@app.post("/attendance")
@app.post("/api/attendance")
def mark_attendance():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    body        = request.get_json(silent=True) or {}
    employee_id = body.get("employee_id")
    att_date    = (body.get("att_date") or "").strip()
    status      = (body.get("status") or "present").strip().lower()
    notes       = (body.get("notes") or "").strip() or None
    marked_by   = payload.get("username", "unknown")

    VALID_STATUSES = ("present", "absent", "half_day", "leave")
    if not employee_id:
        return jsonify({"detail": "employee_id is required"}), 400
    if not att_date:
        return jsonify({"detail": "att_date (YYYY-MM-DD) is required"}), 400
    if status not in VALID_STATUSES:
        return jsonify({"detail": f"status must be one of {VALID_STATUSES}"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM employees WHERE id = %s AND active = TRUE", (employee_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Employee not found or inactive"}), 404

        cur.execute(
            """
            INSERT INTO attendance (employee_id, att_date, status, marked_by, notes)
            VALUES (%s, %s::DATE, %s, %s, %s)
            ON CONFLICT (employee_id, att_date)
            DO UPDATE SET status = EXCLUDED.status,
                          marked_by = EXCLUDED.marked_by,
                          notes = EXCLUDED.notes,
                          updated_at = NOW()
            RETURNING *
            """,
            (employee_id, att_date, status, marked_by, notes),
        )
        att = _emp_to_dict(cur.fetchone())
        conn.commit()
        return jsonify({"message": "Attendance marked", "attendance": att}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Attendance — LIST for a date  (GET /api/attendance?date=YYYY-MM-DD)
# Returns all employees with their attendance status for that day.
# ---------------------------------------------------------------------------

@app.get("/attendance")
@app.get("/api/attendance")
def get_attendance():
    payload, err_resp = require_auth()
    if err_resp:
        return err_resp

    att_date = request.args.get("date", "")
    if not att_date:
        from datetime import date
        att_date = date.today().isoformat()

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute(
            """
            SELECT e.id AS employee_id, e.emp_code, e.full_name, e.role,
                   a.id AS att_id, a.status, a.marked_by, a.notes, a.att_date, a.updated_at
            FROM employees e
            LEFT JOIN attendance a
                   ON a.employee_id = e.id AND a.att_date = %s::DATE
            WHERE e.active = TRUE
            ORDER BY e.full_name
            """,
            (att_date,),
        )
        rows = []
        for r in cur.fetchall():
            d = dict(r)
            for k, v in d.items():
                if isinstance(v, datetime):
                    d[k] = v.isoformat()
                elif hasattr(v, 'isoformat'):
                    d[k] = v.isoformat()
            rows.append(d)
        return jsonify({"attendance": rows, "date": att_date, "total": len(rows)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Attendance — MONTHLY REPORT  (GET /api/attendance/report?month=YYYY-MM)
# Returns each employee's summary: present, absent, half_day, leave counts.
# Admin only.
# ---------------------------------------------------------------------------

@app.get("/attendance/report")
@app.get("/api/attendance/report")
def attendance_report():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    from datetime import date
    month = request.args.get("month", date.today().strftime("%Y-%m"))   # YYYY-MM
    try:
        year, mon = int(month.split("-")[0]), int(month.split("-")[1])
    except Exception:
        return jsonify({"detail": "month must be YYYY-MM"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute(
            """
            SELECT
                e.id AS employee_id,
                e.emp_code,
                e.full_name,
                e.role,
                e.daily_rate,
                COALESCE(SUM(CASE WHEN a.status = 'present'  THEN 1 ELSE 0 END), 0) AS present_days,
                COALESCE(SUM(CASE WHEN a.status = 'absent'   THEN 1 ELSE 0 END), 0) AS absent_days,
                COALESCE(SUM(CASE WHEN a.status = 'half_day' THEN 1 ELSE 0 END), 0) AS half_days,
                COALESCE(SUM(CASE WHEN a.status = 'leave'    THEN 1 ELSE 0 END), 0) AS leave_days
            FROM employees e
            LEFT JOIN attendance a
                   ON a.employee_id = e.id
                  AND EXTRACT(YEAR  FROM a.att_date) = %s
                  AND EXTRACT(MONTH FROM a.att_date) = %s
            WHERE e.active = TRUE
            GROUP BY e.id, e.emp_code, e.full_name, e.role, e.daily_rate
            ORDER BY e.full_name
            """,
            (year, mon),
        )
        report = []
        for r in cur.fetchall():
            present    = int(r["present_days"])
            half       = int(r["half_days"])
            leave      = int(r["leave_days"])
            daily_rate = float(r["daily_rate"])
            # effective days: present=1, half_day=0.5, leave=1 (paid leave), absent=0
            effective  = present + half * 0.5 + leave
            earned     = round(daily_rate * effective, 2)
            report.append({
                "employee_id":  r["employee_id"],
                "emp_code":     r["emp_code"],
                "full_name":    r["full_name"],
                "role":         r["role"],
                "daily_rate":   daily_rate,
                "present_days": present,
                "absent_days":  int(r["absent_days"]),
                "half_days":    half,
                "leave_days":   leave,
                "effective_days": effective,
                "gross_earned": earned,
            })

        # Total salary paid this month per employee (sum of all payments)
        cur.execute(
            """
            SELECT employee_id,
                   COALESCE(SUM(amount_paid), 0) AS total_paid
            FROM salary_payments
            WHERE pay_month = %s
            GROUP BY employee_id
            """,
            (month,),
        )
        paid_map = {row["employee_id"]: float(row["total_paid"]) for row in cur.fetchall()}

        # Total advances given this month (not yet recovered)
        cur.execute(
            """
            SELECT employee_id,
                   COALESCE(SUM(amount), 0) AS total_advance
            FROM advances
            WHERE TO_CHAR(given_on, 'YYYY-MM') = %s
              AND recovered = FALSE
            GROUP BY employee_id
            """,
            (month,),
        )
        advance_map = {row["employee_id"]: float(row["total_advance"]) for row in cur.fetchall()}

        for row in report:
            eid        = row["employee_id"]
            paid       = paid_map.get(eid, 0)
            adv        = advance_map.get(eid, 0)
            balance    = round(row["gross_earned"] - paid - adv, 2)
            row["total_paid"]     = paid
            row["total_advance"]  = adv
            row["balance_due"]    = balance

        return jsonify({"report": report, "month": month})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Salary Payment — ADD PAYOUT  (POST /api/salary/pay)   — Admin only
# Multiple payouts per month allowed (weekly / fortnightly / ad-hoc)
# ---------------------------------------------------------------------------

@app.post("/salary/pay")
@app.post("/api/salary/pay")
def mark_salary_paid():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    body         = request.get_json(silent=True) or {}
    employee_id  = body.get("employee_id")
    pay_month    = (body.get("pay_month") or "").strip()   # YYYY-MM
    amount_paid  = float(body.get("amount_paid", 0))
    payment_type = (body.get("payment_type") or "salary").strip()  # salary | advance
    notes        = (body.get("notes") or "").strip() or None
    paid_by      = admin.get("username", "Admin")

    if not employee_id:
        return jsonify({"detail": "employee_id is required"}), 400
    if not pay_month:
        return jsonify({"detail": "pay_month (YYYY-MM) is required"}), 400
    if amount_paid <= 0:
        return jsonify({"detail": "amount_paid must be > 0"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM employees WHERE id = %s", (employee_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Employee not found"}), 404
        cur.execute(
            """
            INSERT INTO salary_payments (employee_id, pay_month, amount_paid, payment_type, paid_by, notes)
            VALUES (%s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (employee_id, pay_month, amount_paid, payment_type, paid_by, notes),
        )
        sp = _emp_to_dict(cur.fetchone())
        conn.commit()
        return jsonify({"message": "Payment recorded", "salary_payment": sp}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Salary — LIST payments for an employee+month  (GET /api/salary/payments)
# ---------------------------------------------------------------------------

@app.get("/salary/payments")
@app.get("/api/salary/payments")
def list_salary_payments():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    employee_id = request.args.get("employee_id")
    pay_month   = request.args.get("month")

    if not employee_id or not pay_month:
        return jsonify({"detail": "employee_id and month are required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute(
            "SELECT * FROM salary_payments WHERE employee_id = %s AND pay_month = %s ORDER BY paid_at",
            (employee_id, pay_month),
        )
        payments = [_emp_to_dict(r) for r in cur.fetchall()]
        return jsonify({"payments": payments, "total": len(payments)})
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Advances — GIVE ADVANCE  (POST /api/advances)   — Admin only
# ---------------------------------------------------------------------------

@app.post("/advances")
@app.post("/api/advances")
def give_advance():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    body        = request.get_json(silent=True) or {}
    employee_id = body.get("employee_id")
    amount      = float(body.get("amount", 0))
    given_on    = (body.get("given_on") or "").strip() or None
    notes       = (body.get("notes") or "").strip() or None
    given_by    = admin.get("username", "Admin")

    if not employee_id:
        return jsonify({"detail": "employee_id is required"}), 400
    if amount <= 0:
        return jsonify({"detail": "amount must be > 0"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM employees WHERE id = %s", (employee_id,))
        if not cur.fetchone():
            return jsonify({"detail": "Employee not found"}), 404
        cur.execute(
            """
            INSERT INTO advances (employee_id, amount, given_on, given_by, notes)
            VALUES (%s, %s, COALESCE(%s::DATE, CURRENT_DATE), %s, %s)
            RETURNING *
            """,
            (employee_id, amount, given_on, given_by, notes),
        )
        adv = _emp_to_dict(cur.fetchone())
        conn.commit()
        return jsonify({"message": "Advance recorded", "advance": adv}), 201
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Advances — LIST for an employee  (GET /api/advances?employee_id=&month=)
# ---------------------------------------------------------------------------

@app.get("/advances")
@app.get("/api/advances")
def list_advances():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    employee_id = request.args.get("employee_id")
    month       = request.args.get("month")   # YYYY-MM, optional

    if not employee_id:
        return jsonify({"detail": "employee_id is required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        if month:
            cur.execute(
                "SELECT * FROM advances WHERE employee_id = %s AND TO_CHAR(given_on,'YYYY-MM') = %s ORDER BY given_on",
                (employee_id, month),
            )
        else:
            cur.execute(
                "SELECT * FROM advances WHERE employee_id = %s ORDER BY given_on DESC LIMIT 50",
                (employee_id,),
            )
        advances = [_emp_to_dict(r) for r in cur.fetchall()]
        return jsonify({"advances": advances, "total": len(advances)})
    finally:
        cur.close(); conn.close()
