import os
import urllib.parse
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent / ".env")

import jwt
import psycopg2
from psycopg2.extras import RealDictCursor
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from passlib.context import CryptContext
from werkzeug.security import check_password_hash as werkzeug_check

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(title="Crown Tea Hub Billing API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

VALID_ROLES   = ("Admin", "Cashier")
JWT_SECRET    = os.environ.get("SECRET_KEY", "dev-secret-key")
JWT_ALGORITHM = "HS256"
JWT_EXP_HOURS = 12

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
bearer      = HTTPBearer()

# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _get_dsn() -> str:
    dsn = os.environ.get("DATABASE_URL", "")
    if not dsn:
        raise RuntimeError("DATABASE_URL not set")
    parsed = urllib.parse.urlparse(dsn)
    params = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
    params.pop("channel_binding", None)
    new_query = urllib.parse.urlencode({k: v[0] for k, v in params.items()})
    return parsed._replace(query=new_query).geturl()


def get_conn():
    return psycopg2.connect(_get_dsn(), connect_timeout=15)


def get_cur(conn):
    return conn.cursor(cursor_factory=RealDictCursor)


# ---------------------------------------------------------------------------
# DB init — runs once per cold start
# ---------------------------------------------------------------------------

_db_ready = False


def ensure_db():
    global _db_ready
    if _db_ready:
        return
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    username      VARCHAR(100) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    full_name     VARCHAR(150) NOT NULL,
                    active        BOOLEAN      NOT NULL DEFAULT TRUE,
                    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS roles (
                    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name       VARCHAR(50) NOT NULL UNIQUE,
                    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS user_roles (
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    role_id BIGINT NOT NULL REFERENCES roles(id),
                    PRIMARY KEY (user_id, role_id)
                )
            """)
            cur.execute("""
                INSERT INTO roles (name) VALUES ('Admin'), ('Cashier')
                ON CONFLICT (name) DO NOTHING
            """)
        conn.commit()
        _db_ready = True
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

def _create_token(user_id: int, username: str, role: str) -> str:
    payload = {
        "sub": str(user_id),
        "username": username,
        "role": role,
        "exp": datetime.now(timezone.utc) + timedelta(hours=JWT_EXP_HOURS),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)


def _decode_token(token: str) -> dict:
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        raise HTTPException(401, "Token has expired")
    except jwt.InvalidTokenError:
        raise HTTPException(401, "Invalid token")


# ---------------------------------------------------------------------------
# Auth dependencies
# ---------------------------------------------------------------------------

def get_current_user(creds: HTTPAuthorizationCredentials = Depends(bearer)) -> dict:
    """Decode token and return payload. Any logged-in user passes."""
    return _decode_token(creds.credentials)


def require_admin(creds: HTTPAuthorizationCredentials = Depends(bearer)) -> dict:
    """Decode token and enforce Admin role."""
    payload = _decode_token(creds.credentials)
    if payload.get("role") != "Admin":
        raise HTTPException(403, "Admin role required")
    return payload


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _user_to_dict(row: dict) -> dict:
    d = dict(row)
    d.pop("password_hash", None)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
    return d


def _get_user_role(cur, user_id) -> str | None:
    cur.execute(
        """
        SELECT r.name FROM roles r
        JOIN user_roles ur ON ur.role_id = r.id
        WHERE ur.user_id = %s LIMIT 1
        """,
        (user_id,),
    )
    row = cur.fetchone()
    return row["name"] if row else None


def _assign_role(cur, user_id, role_name: str):
    cur.execute("SELECT id FROM roles WHERE name = %s", (role_name,))
    role = cur.fetchone()
    if not role:
        raise ValueError(f"Role '{role_name}' does not exist. Valid: {VALID_ROLES}")
    cur.execute("DELETE FROM user_roles WHERE user_id = %s", (user_id,))
    cur.execute(
        "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s)",
        (user_id, role["id"]),
    )


def _verify_password(plain: str, hashed: str) -> bool:
    if hashed.startswith(("scrypt:", "pbkdf2:", "sha256$")):
        return werkzeug_check(hashed, plain)
    return pwd_context.verify(plain, hashed)


def _needs_rehash(hashed: str) -> bool:
    return hashed.startswith(("scrypt:", "pbkdf2:", "sha256$"))


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class RegisterRequest(BaseModel):
    username:  str
    password:  str
    full_name: str
    role:      str


class LoginRequest(BaseModel):
    username: str
    password: str


class UpdateUserRequest(BaseModel):
    username:  Optional[str]  = None
    password:  Optional[str]  = None
    full_name: Optional[str]  = None
    active:    Optional[bool] = None
    role:      Optional[str]  = None


# ---------------------------------------------------------------------------
# Public routes
# ---------------------------------------------------------------------------

@app.get("/health")
@app.get("/")
def health():
    try:
        conn = get_conn()
        conn.cursor().execute("SELECT 1")
        conn.close()
        return {"status": "healthy", "message": "Billing API is running", "db": "connected"}
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "unhealthy", "error": str(e)})


@app.post("/api/login")
def login(body: LoginRequest):
    """
    Authenticate user and return a JWT token with role.

    Request:
        { "username": "...", "password": "..." }

    Response:
        {
          "message": "Login successful",
          "token": "<jwt>",
          "token_type": "bearer",
          "user": { "id", "username", "full_name", "role", "active", ... }
        }
    """
    ensure_db()
    username = body.username.strip()
    password = body.password.strip()

    if not username or not password:
        raise HTTPException(400, "username and password are required")

    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cur.fetchone()

        if not user or not _verify_password(password, user["password_hash"]):
            raise HTTPException(401, "Invalid username or password")
        if not user["active"]:
            raise HTTPException(403, "Account is disabled")

        # Migrate legacy Werkzeug hash → bcrypt on first successful login
        if _needs_rehash(user["password_hash"]):
            cur.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (pwd_context.hash(password), user["id"]),
            )
            conn.commit()

        role      = _get_user_role(cur, user["id"])
        token     = _create_token(user["id"], user["username"], role)
        user_data = _user_to_dict(user)
        user_data["role"] = role

        return {
            "message":    "Login successful",
            "token":      token,
            "token_type": "bearer",
            "user":       user_data,
        }
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Admin-only routes  (require Authorization: Bearer <token> with role=Admin)
# ---------------------------------------------------------------------------

@app.post("/api/register", status_code=201)
def register(body: RegisterRequest, admin: dict = Depends(require_admin)):
    """
    Register a new user. Admin role required.

    Headers:
        Authorization: Bearer <token>

    Request:
        { "username": "...", "password": "...", "full_name": "...", "role": "Admin|Cashier" }
    """
    ensure_db()
    username  = body.username.strip()
    password  = body.password.strip()
    full_name = body.full_name.strip()
    role      = body.role.strip()

    if not username or not password or not full_name:
        raise HTTPException(400, "username, password, and full_name are required")
    if role not in VALID_ROLES:
        raise HTTPException(400, f"role must be one of {VALID_ROLES}")

    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE username = %s", (username,))
        if cur.fetchone():
            raise HTTPException(409, "Username already exists")
        cur.execute(
            "INSERT INTO users (username, password_hash, full_name) VALUES (%s, %s, %s) RETURNING *",
            (username, pwd_context.hash(password), full_name),
        )
        user_row = cur.fetchone()
        _assign_role(cur, user_row["id"], role)
        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = role
        return {"message": "User created successfully", "user": user}
    except HTTPException:
        conn.rollback(); raise
    except ValueError as e:
        conn.rollback(); raise HTTPException(400, str(e))
    except Exception as e:
        conn.rollback(); raise HTTPException(400, str(e))
    finally:
        cur.close(); conn.close()


@app.get("/api/users")
def list_users(admin: dict = Depends(require_admin)):
    """
    List all users. Admin role required.

    Headers:
        Authorization: Bearer <token>
    """
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users ORDER BY id")
        users = []
        for row in cur.fetchall():
            u = _user_to_dict(row)
            u["role"] = _get_user_role(cur, row["id"])
            users.append(u)
        return {"users": users, "total": len(users)}
    finally:
        cur.close(); conn.close()


@app.put("/api/users/{user_id}")
def update_user(user_id: int, body: UpdateUserRequest, admin: dict = Depends(require_admin)):
    """
    Update a user. Admin role required.

    Headers:
        Authorization: Bearer <token>
    """
    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE id = %s", (user_id,))
        if not cur.fetchone():
            raise HTTPException(404, "User not found")

        fields, values = [], []
        if body.full_name and body.full_name.strip():
            fields.append("full_name = %s"); values.append(body.full_name.strip())
        if body.username and body.username.strip():
            fields.append("username = %s"); values.append(body.username.strip())
        if body.password and body.password.strip():
            fields.append("password_hash = %s"); values.append(pwd_context.hash(body.password.strip()))
        if body.active is not None:
            fields.append("active = %s"); values.append(body.active)

        if fields:
            fields.append("updated_at = NOW()")
            values.append(user_id)
            cur.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
            user_row = cur.fetchone()
        else:
            cur.execute("SELECT * FROM users WHERE id = %s", (user_id,))
            user_row = cur.fetchone()

        new_role = body.role.strip() if body.role else ""
        if new_role:
            if new_role not in VALID_ROLES:
                raise HTTPException(400, f"role must be one of {VALID_ROLES}")
            _assign_role(cur, user_id, new_role)

        if not fields and not new_role:
            raise HTTPException(400, "No valid fields provided to update")

        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = _get_user_role(cur, user_id)
        return {"message": "User updated successfully", "user": user}
    except HTTPException:
        conn.rollback(); raise
    except ValueError as e:
        conn.rollback(); raise HTTPException(400, str(e))
    except Exception as e:
        conn.rollback(); raise HTTPException(400, str(e))
    finally:
        cur.close(); conn.close()
