import os
import urllib.parse
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent / ".env")

import jwt
import psycopg2
from psycopg2.extras import RealDictCursor
from flask import Flask, request, jsonify
from flask_cors import CORS
from passlib.context import CryptContext
from werkzeug.security import check_password_hash as werkzeug_check

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = Flask(__name__)
CORS(app)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

VALID_ROLES   = ("Admin", "Cashier")
JWT_SECRET    = os.environ.get("SECRET_KEY", "dev-secret-key")
JWT_ALGORITHM = "HS256"
JWT_EXP_HOURS = 12

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

def _get_dsn() -> str:
    dsn = os.environ.get("DATABASE_URL", "")
    if not dsn:
        raise RuntimeError("DATABASE_URL not set")
    parsed = urllib.parse.urlparse(dsn)
    params = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
    params.pop("channel_binding", None)
    new_query = urllib.parse.urlencode({k: v[0] for k, v in params.items()})
    return parsed._replace(query=new_query).geturl()


def get_conn():
    return psycopg2.connect(_get_dsn(), connect_timeout=15)


def get_cur(conn):
    return conn.cursor(cursor_factory=RealDictCursor)


# ---------------------------------------------------------------------------
# DB init — runs once per cold start
# ---------------------------------------------------------------------------

_db_ready = False


def ensure_db():
    global _db_ready
    if _db_ready:
        return
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    username      VARCHAR(100) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    full_name     VARCHAR(150) NOT NULL,
                    active        BOOLEAN      NOT NULL DEFAULT TRUE,
                    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS roles (
                    id         BIGINT      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name       VARCHAR(50) NOT NULL UNIQUE,
                    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS user_roles (
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    role_id BIGINT NOT NULL REFERENCES roles(id),
                    PRIMARY KEY (user_id, role_id)
                )
            """)
            cur.execute("""
                INSERT INTO roles (name) VALUES ('Admin'), ('Cashier')
                ON CONFLICT (name) DO NOTHING
            """)
        conn.commit()
        _db_ready = True
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

def _create_token(user_id: int, username: str, role: str) -> str:
    payload = {
        "sub": str(user_id),
        "username": username,
        "role": role,
        "exp": datetime.now(timezone.utc) + timedelta(hours=JWT_EXP_HOURS),
    }
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGORITHM)


def _decode_token(token: str) -> dict:
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        return None, "Token has expired"
    except jwt.InvalidTokenError:
        return None, "Invalid token"


# ---------------------------------------------------------------------------
# Auth middleware helpers
# ---------------------------------------------------------------------------

def _get_token_from_request():
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return None, "Missing or invalid Authorization header"
    token = auth.split(" ", 1)[1]
    result = _decode_token(token)
    if isinstance(result, tuple):
        return None, result[1]
    return result, None


def require_auth():
    payload, err = _get_token_from_request()
    if err:
        return None, (jsonify({"detail": err}), 401)
    return payload, None


def require_admin():
    payload, err_resp = require_auth()
    if err_resp:
        return None, err_resp
    if payload.get("role") != "Admin":
        return None, (jsonify({"detail": "Admin role required"}), 403)
    return payload, None


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _user_to_dict(row: dict) -> dict:
    d = dict(row)
    d.pop("password_hash", None)
    for k, v in d.items():
        if isinstance(v, datetime):
            d[k] = v.isoformat()
    return d


def _get_user_role(cur, user_id) -> str | None:
    cur.execute(
        """
        SELECT r.name FROM roles r
        JOIN user_roles ur ON ur.role_id = r.id
        WHERE ur.user_id = %s LIMIT 1
        """,
        (user_id,),
    )
    row = cur.fetchone()
    return row["name"] if row else None


def _assign_role(cur, user_id, role_name: str):
    cur.execute("SELECT id FROM roles WHERE name = %s", (role_name,))
    role = cur.fetchone()
    if not role:
        raise ValueError(f"Role '{role_name}' does not exist. Valid: {VALID_ROLES}")
    cur.execute("DELETE FROM user_roles WHERE user_id = %s", (user_id,))
    cur.execute(
        "INSERT INTO user_roles (user_id, role_id) VALUES (%s, %s)",
        (user_id, role["id"]),
    )


def _verify_password(plain: str, hashed: str) -> bool:
    if hashed.startswith(("scrypt:", "pbkdf2:", "sha256$")):
        return werkzeug_check(hashed, plain)
    return pwd_context.verify(plain, hashed)


def _needs_rehash(hashed: str) -> bool:
    return hashed.startswith(("scrypt:", "pbkdf2:", "sha256$"))


# ---------------------------------------------------------------------------
# Public routes
# ---------------------------------------------------------------------------

@app.get("/health")
@app.get("/api/health")
@app.get("/")
def health():
    try:
        conn = get_conn()
        conn.cursor().execute("SELECT 1")
        conn.close()
        return jsonify({"status": "healthy", "message": "Billing API is running", "db": "connected"})
    except Exception as e:
        return jsonify({"status": "unhealthy", "error": str(e)}), 500


@app.post("/login")
@app.post("/api/login")
def login():
    body = request.get_json(force=True, silent=True)
    if not body:
        import json
        try:
            body = json.loads(request.data.decode("utf-8"))
        except Exception:
            body = {}
    username = (body.get("username") or "").strip()
    password = (body.get("password") or "").strip()

    if not username or not password:
        return jsonify({"detail": "username and password are required"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users WHERE username = %s", (username,))
        user = cur.fetchone()

        if not user or not _verify_password(password, user["password_hash"]):
            return jsonify({"detail": "Invalid username or password"}), 401
        if not user["active"]:
            return jsonify({"detail": "Account is disabled"}), 403

        # Migrate legacy Werkzeug hash → bcrypt on first successful login
        if _needs_rehash(user["password_hash"]):
            cur.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (pwd_context.hash(password), user["id"]),
            )
            conn.commit()

        role      = _get_user_role(cur, user["id"])
        token     = _create_token(user["id"], user["username"], role)
        user_data = _user_to_dict(user)
        user_data["role"] = role

        return jsonify({
            "message":    "Login successful",
            "token":      token,
            "token_type": "bearer",
            "user":       user_data,
        })
    finally:
        cur.close(); conn.close()


# ---------------------------------------------------------------------------
# Admin-only routes  (require Authorization: Bearer <token> with role=Admin)
# ---------------------------------------------------------------------------

@app.post("/register")
@app.post("/api/register")
def register():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    body = request.get_json(force=True, silent=True)
    if not body:
        import json
        try:
            body = json.loads(request.data.decode("utf-8"))
        except Exception:
            body = {}
    username  = (body.get("username") or "").strip()
    password  = (body.get("password") or "").strip()
    full_name = (body.get("full_name") or "").strip()
    role      = (body.get("role") or "").strip()

    if not username or not password or not full_name:
        return jsonify({"detail": "username, password, and full_name are required"}), 400
    if role not in VALID_ROLES:
        return jsonify({"detail": f"role must be one of {VALID_ROLES}"}), 400

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE username = %s", (username,))
        if cur.fetchone():
            return jsonify({"detail": "Username already exists"}), 409
        cur.execute(
            "INSERT INTO users (username, password_hash, full_name) VALUES (%s, %s, %s) RETURNING *",
            (username, pwd_context.hash(password), full_name),
        )
        user_row = cur.fetchone()
        _assign_role(cur, user_row["id"], role)
        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = role
        return jsonify({"message": "User created successfully", "user": user}), 201
    except ValueError as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()


@app.get("/users")
@app.get("/api/users")
def list_users():
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT * FROM users ORDER BY id")
        users = []
        for row in cur.fetchall():
            u = _user_to_dict(row)
            u["role"] = _get_user_role(cur, row["id"])
            users.append(u)
        return jsonify({"users": users, "total": len(users)})
    finally:
        cur.close(); conn.close()


@app.put("/users/<int:user_id>")
@app.put("/api/users/<int:user_id>")
def update_user(user_id: int):
    admin, err_resp = require_admin()
    if err_resp:
        return err_resp

    ensure_db()
    conn = get_conn()
    cur  = get_cur(conn)
    try:
        cur.execute("SELECT id FROM users WHERE id = %s", (user_id,))
        if not cur.fetchone():
            return jsonify({"detail": "User not found"}), 404

        body = request.get_json(force=True, silent=True)
        if not body:
            import json
            try:
                body = json.loads(request.data.decode("utf-8"))
            except Exception:
                body = {}
        fields, values = [], []

        full_name = (body.get("full_name") or "").strip()
        username  = (body.get("username") or "").strip()
        password  = (body.get("password") or "").strip()
        active    = body.get("active")
        new_role  = (body.get("role") or "").strip()

        if full_name:
            fields.append("full_name = %s"); values.append(full_name)
        if username:
            fields.append("username = %s"); values.append(username)
        if password:
            fields.append("password_hash = %s"); values.append(pwd_context.hash(password))
        if active is not None:
            fields.append("active = %s"); values.append(active)

        if fields:
            fields.append("updated_at = NOW()")
            values.append(user_id)
            cur.execute(f"UPDATE users SET {', '.join(fields)} WHERE id = %s RETURNING *", values)
            user_row = cur.fetchone()
        else:
            cur.execute("SELECT * FROM users WHERE id = %s", (user_id,))
            user_row = cur.fetchone()

        if new_role:
            if new_role not in VALID_ROLES:
                return jsonify({"detail": f"role must be one of {VALID_ROLES}"}), 400
            _assign_role(cur, user_id, new_role)

        if not fields and not new_role:
            return jsonify({"detail": "No valid fields provided to update"}), 400

        conn.commit()
        user = _user_to_dict(user_row)
        user["role"] = _get_user_role(cur, user_id)
        return jsonify({"message": "User updated successfully", "user": user})
    except ValueError as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    except Exception as e:
        conn.rollback()
        return jsonify({"detail": str(e)}), 400
    finally:
        cur.close(); conn.close()
